### ISSUE TITLE
Incorrect permissions on windows during tests

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-authentication-oauth2#8]
- [x] I was not able to find an [open](https://github.com/zendframework/zend-expressive-authentication-oauth2/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-expressive-authentication-oauth2/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [x] This is not a question. (Questions should be asked on [slack](https://zendframework.slack.com/) ([Signup for Slack here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/).)

Provide a narrative description of what you are trying to accomplish.

### Code to reproduce the issue

Run `composer test` on windows

### Expected results

Tests pass.

### Actual results

1) ZendTest\Expressive\Authentication\OAuth2\AuthorizationServerFactoryTest::testInvokeWithValidData
Key file "file://~\Projects\zendframwork\zend-expressive-authentication-oauth2\test/TestAsset/private.key" permissions are not correct, should be 600 or 660 instead of 666

---

Originally posted by @geerteltink at https://github.com/zendframework/zend-expressive-authentication-oauth2/issues/10

**Comment by weierophinney** [comment]
I have the same problem some way to fix

---

Originally posted by @RodriAndreotti at https://github.com/zendframework/zend-expressive-authentication-oauth2/issues/10#issuecomment-424538896

**Comment by arueckauer** [comment]
The issue is caused in league/oauth2-server due to Windows having a different approach for file permissions.

There are several issues/requests for it to implement compatibility for the Windows file permission system ([one example](https://github.com/thephpleague/oauth2-server/issues/779)). However this is rather difficult.

An alternative could be to disable permission check when running tests on Windows, but that complicates test scenarios. Also there is no Windows build in the CI, this would make tests not transparent... For development purposes I would suggest using e.g. WSL2.

IMO this can be closed.

**Comment by froschdesign** [comment]
If there are ideas how to solve the problem here on GitHub and / or in local development environment, please create a new issue report or better a pull request.
